language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "python manage.py migrate"
  - docker-compose run web sh -c "python manage.py test"

deploy:
  provider: heroku
  api_key:
    secure: 12354487-fe77-4d39-bf16-e1903e02a9fc
  app: stckrunsbackend
  on:
    repo: ugwumadu116/stockRunsBackend

