version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
        - TESTER=1
        - SECRET_KEY=lioear+t2m)w8tqh3!#=9keq+ldz^4dpe5h*a4k*5c=@%-y@nw
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migration

  migration:
    build: .
    command: python manage.py migrate
    depends_on:
      - db


