# Generated by Django 2.2.7 on 2019-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20191129_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystockfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
